FILES = $(addsuffix .xa,  $(basename $(wildcard iso/songs/*/*.ogg) $(wildcard iso/music/*.ogg))) \
  $(basename $(wildcard iso/music/*.txt) $(wildcard iso/songs/*.txt))

all: \
  $(FILES) \

# XA converts
iso/%.xa: iso/%.ogg
	tools/psxavenc/psxavenc -f 37800 -t xa -b 4 -c 2 -F 1 -C 0 $< $@
iso/%.xa:
	tools/xainterleave/xainterleave $@

.PHONY: clean
clean:
	rm -f $(FILES)
