all: \
	iso/music/freakymenu/freakymenu.mus \
	iso/music/gameover/gameover.mus \
	\
	\
	\
	iso/songs/bopeebo/bopeebo.mus \
	iso/songs/fresh/fresh.mus \
	iso/songs/dadbattle/dadbattle.mus \
	iso/songs/tutorial/tutorial.mus \

iso/%.mus: iso/%.txt
	tools/funkinmuspak/funkinmuspak $@ $<
