all: \
	iso/music/freakymenu/freakymenu.mus \
	iso/music/gameover/gameover.mus \
	iso/sounds/fnf_loss_sfx/fnf_loss_sfx.mus \
	iso/songs/bopeebo/bopeebo.mus \
	iso/songs/fresh/fresh.mus \
	iso/songs/dadbattle/dadbattle.mus \
	iso/songs/tutorial/tutorial.mus \
	iso/songs/devils-gambit/devils-gambit.mus \
	iso/songs/too-slow/too-slow.mus \

iso/%.mus: iso/%.txt
	tools/funkinmuspak/funkinmuspak $@ $<
