FILES = $(addsuffix .xa,  $(basename $(wildcard iso/songs/*/*.ogg))) \
  $(basename $(wildcard iso/songs/*.txt))

all: \
	iso/music/menu.xa \
	$(FILES) \

# XA converts
iso/%.xa: iso/%.ogg
	tools/psxavenc/psxavenc -f 37800 -t xa -b 4 -c 2 -F 1 -C 0 $< $@
iso/%.xa:
	tools/xainterleave/xainterleave $@

# Menu
iso/music/menu.xa: iso/music/freakymenu.xa iso/music/gameover.xa
